### ISSUE TITLE
Openshift build failing on OSX El Capitan - 

### ISSUE THREAD

**Issue by vvaka** [nak3/homebrew-openshift#2] opened 2015-08-26 16:07 UTC
attached the gist logs
https://gist.github.com/anonymous/083c2353cf3d24bacaf7

**Comment by adrianluisgonzalez** [comment] 2015-09-09 02:50
I had a similar problem on Yosemite with v1.0.5.  Version 1.0.4 was working fine.  Here's the contents of the log file `01.make`:

```
make
all
WHAT=cmd/openshift
GOFLAGS=-v

hack/build-go.sh cmd/openshift
++ Building go targets for darwin/amd64: cmd/openshift
package github.com/openshift/origin/cmd/openshift
        imports github.com/openshift/origin/pkg/cmd/openshift
        imports github.com/openshift/origin/pkg/cmd/admin
        imports github.com/openshift/origin/pkg/cmd/admin/cert
        imports github.com/openshift/origin/pkg/cmd/server/admin
        imports github.com/openshift/origin/pkg/cmd/cli/describe
        imports github.com/gonum/graph/internal: use of internal package not allowed
make: *** [all] Error 1

HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 2b624dc1639ac67017ea5ed1ef7aa6a87137256a
Last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit haswell
OS X: 10.10.5-x86_64
Xcode: 6.4
CLT: 6.4.0.0.1.1435007323
GCC-4.2: build 0
Clang: 6.1 build 602
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: 1.8.0_51

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/local/opt/go/bin:/usr/local/opt/git/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by nak3** [comment] 2015-09-10 07:02
Thank you @vvaka and @adrianluisgonzalez, and sorry for my late reply.

The root cause is that most of the Mac environment already has Go 1.5 and it has new [internal package function](https://blog.golang.org/go1.5).


The troubled package will be fixed. - https://github.com/openshift/origin/pull/4324/files#diff-21028052c2cb37c2d299ccf7b678d9beL11
So, it seems better to wait for update to v1.0.5 until Go1.5 support for Origin. https://github.com/openshift/origin/pull/4324

Now I downgraded homebrew-openshift to v1.0.4 and you can use it.

**Comment by adrianluisgonzalez** [comment] 2015-09-10 14:46
@nak3, thanks for the info.

**Comment by nak3** [comment] 2015-10-24 12:01
Just FYI: https://github.com/openshift/origin/pull/4324 has been closed, but we need to wait for new tag v1.0.7.

**Comment by nak3** [comment] 2015-10-30 02:46
I updated to v1.0.7. If you got following error, you may need to `untap`/`tap` and update.

~~~
% brew update
error: insufficient permission for adding an object to repository database .git/objects
fatal: failed to write object
fatal: unpack-objects failed
Error: Failed to update tap: nak3/openshift
Already up-to-date.
~~~

- Solution

~~~
% sudo brew untap nak3/openshift
% brew tap nak3/openshift
% brew install nak3/openshift/openshift
~~~

**Comment by adrianluisgonzalez** [comment] 2015-11-09 19:10
thanks, works for me.

**Comment by nak3** [comment] 2015-11-10 04:34
Thank you @adrianluisgonzalez 
@vvaka I will close this issue, but if you hit any issue regarding this, please feel free to re-open.

**Closed by nak3** 2015-11-10 04:34 UTC
